# Écoute sur toutes les interfaces
listening-ip=0.0.0.0
listening-port=3478

# Plage de ports pour les relais (doit correspondre au docker-compose)
min-port=49160
max-port=49200

# Authentification statique
lt-cred-mech
user=visio:visiopass

# Realm
realm=visio.local

# Sécurité
fingerprint
stale-nonce=600
total-quota=100

# Logs simples
simple-log
