FROM kirito140/olga-designer:latest

COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./config/config.json /usr/share/nginx/html/config/config.json
COPY ./config/local.config /usr/share/nginx/html/local.config
COPY ./config/domain_config.json /usr/share/nginx/html/domain_config.json